package main

import (
	"mangosteen/cmd"
	"mangosteen/config"

	// replace it with your package path
	_ "mangosteen/docs" // docs is generated by Swag CLI, you have to import it.
)

//	@title			Mangosteen API
//	@description	Swagger 2.0 Standard API doc

//	@contact.name	null
//	@contact.url	https://songen.me
//	@contact.email	songen@foxmail.com

//	@host		localhost:8080
//	@BasePath	/

//	@securityDefinitions.basic	BasicAuth(JWT)

//	@externalDocs.description	OpenAPI
//	@externalDocs.url			https://swagger.io/resources/open-api/

func main() {
	config.LoadAppConfig()

	cmd.Run()
}
