info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: get string by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Show an account
      tags:
      - ping
swagger: "2.0"
